### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by RuiyanNi** [tvseg/MM-LLM-RO#1]
Hi, thanks for the great work! 

When will the code be released?

**Comment by tvseg** [comment]
We appreciate your interests in our work. 
Currently, the manuscript is undergoing the review process, and we anticipate the code could be released around next February. 
We will keep you informed if the review process concludes sooner.

**Comment by tvseg** [comment]
We are happy to inform you that the initial version of our code is released. Please check the code, and note that further readme file will be updated!
