### ISSUE TITLE
Issue with Axis Error When Using Sample Dataset

### ISSUE THREAD

**Issue by lees12Penn** [tvseg/MM-LLM-RO#2]
Hello,

I've been trying to use your pretrained model with the sample dataset available at https://1drv.ms/u/s!AhwNodepZ41oi5c2-gC9wn104Db6UQ?e=geDlPs that you provided, but I'm experiencing a problem while running the inference. Specifically, I am running into an 'AxisError' related to a 'numpy.swapaxes' operation, which seems to indicate that there's an issue with the data dimensions expected versus what is being processed.

Here's the error message resulted from inference:
python main.py --pretrained_dir ./ckpt/multimodal --context True --n_prompts 2 --context_length 8 --test_mode 2

0  gpu 0
Batch size is: 2 epochs 101
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  6.02it/s]
N0, cT2, breast conserving surgery, left side
N0, cT1, breast conserving surgery, right side
N1, cT1c, breast conserving surgery, left side
N1, cT2, breast conserving surgery, right side
>>>>>>> ratio:  1.0
>>>>>>> trainset:  0
>>>>>>> valset:  0
>>>>>>> context:  True
Total parameters count 21486688
Traceback (most recent call last):
  File "E:\MM-LLM-RO\main.py", line 277, in <module>
    main(args)
  File "E:\MM-LLM-RO\main.py", line 45, in main
    main_worker(gpu=0, args=args)
  File "E:\MM-LLM-RO\main.py", line 162, in main_worker
    accuracy = test_model(
  File "E:\MM-LLM-RO\trainer.py", line 158, in test_model
    dice_list_organ = np.swapaxes(np.array(dice_list_organ), 0, 1)
  File "<__array_function__ internals>", line 200, in swapaxes
  File "E:\conda_env\MM-LLM-RO\lib\site-packages\numpy\core\fromnumeric.py", line 594, in swapaxes
    return _wrapfunc(a, 'swapaxes', axis1, axis2)
  File "E:\conda_env\MM-LLM-RO\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
numpy.AxisError: axis2: axis 1 is out of bounds for array of dimension 1

Could you please provide guidance on how this issue might be resolved? Is there a particular aspect of the sample data or configuration that I should verify?

**Comment by tvseg** [comment]
Thanks for your patient. From the provided error message, I find "valset: 0", which indicates that sample CT scans are not properly loaded. Could you confirm the repository of the sample dataset, by following the guidance 2. Dataset in README.MD file?
